[build]
builder = "nixpacks"

[deploy]
startCommand = "echo 'This is a monorepo. Please deploy individual services.'"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

# This is a monorepo configuration
# Individual services should be deployed separately:
# - API service: root directory = api
# - Web service: root directory = web-app 