[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
startCommand = "npm start"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
port = 8080

# Build arguments for different services
[build.args]
SERVICE_DIR = "api"
SERVICE_PORT = "8080" 