version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: bizflow-postgres
    environment:
      POSTGRES_DB: bizflow_dev
      POSTGRES_USER: bizflow
      POSTGRES_PASSWORD: bizflow_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./api/database/init:/docker-entrypoint-initdb.d
    networks:
      - bizflow-network

  # Redis Cache
  redis:
    image: redis:7-alpine
    container_name: bizflow-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    networks:
      - bizflow-network

  # API Service
  api:
    build:
      context: ./api
      dockerfile: Dockerfile.dev
    container_name: bizflow-api
    environment:
      NODE_ENV: development
      DATABASE_URL: postgresql://bizflow:bizflow_password@postgres:5432/bizflow_dev
      REDIS_URL: redis://redis:6379
      JWT_SECRET: dev_jwt_secret_key_change_in_production
      PORT: 4000
    ports:
      - "4000:4000"
    volumes:
      - ./api:/app
      - /app/node_modules
    depends_on:
      - postgres
      - redis
    networks:
      - bizflow-network
    command: npm run dev

  # Web Application
  web:
    build:
      context: ./web-app
      dockerfile: Dockerfile.dev
    container_name: bizflow-web
    environment:
      NODE_ENV: development
      NEXT_PUBLIC_API_URL: http://localhost:4000/graphql
      NEXT_PUBLIC_APP_URL: http://localhost:3000
    ports:
      - "3000:3000"
    volumes:
      - ./web-app:/app
      - /app/node_modules
    depends_on:
      - api
    networks:
      - bizflow-network
    command: npm run dev

  # Elasticsearch (for search and analytics)
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.0
    container_name: bizflow-elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "9200:9200"
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    networks:
      - bizflow-network

  # Mailhog (for email testing in development)
  mailhog:
    image: mailhog/mailhog:latest
    container_name: bizflow-mailhog
    ports:
      - "1025:1025"  # SMTP port
      - "8025:8025"  # Web UI port
    networks:
      - bizflow-network

  # Adminer (Database management UI)
  adminer:
    image: adminer:latest
    container_name: bizflow-adminer
    ports:
      - "8080:8080"
    environment:
      ADMINER_DEFAULT_SERVER: postgres
    depends_on:
      - postgres
    networks:
      - bizflow-network

volumes:
  postgres_data:
  redis_data:
  elasticsearch_data:

networks:
  bizflow-network:
    driver: bridge